// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

 public class Node
    {
        public int[] position;
        public Node previous;
        public int pathLengthFromOrigin;
        public int f;
        public int[] directionFromParent;
        public Node(int[] aPosition, Node aPrevious, int aPathLength, int aF, int[] aDirection)
        {
            position = aPosition;
            previous = aPrevious;
            pathLengthFromOrigin = aPathLength;
            f = aF;
            directionFromParent = aDirection == null ? null : (int[])aDirection.Clone();
        }
    }


